global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['grievance-api:8080']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']